---
### Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{confvolumename}}
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi