---
- hosts: localhost
  tasks:
  - name: Clean up the directory
    file: path=/tmp/k8s/bamboo state=absent

  - name: Create the tmp directory
    file: path=/tmp/k8s/bamboo state=directory

  - name: Render files template to /tmp/k8s/bamboo
    template: src={{ item }} dest=/tmp/k8s/bamboo/{{ item | basename }}
    with_fileglob: "{{playbook_dir}}/*.yml"
    # You can add extra conditional stuff here, example
    #when cluster_name in ["cluster1"]


  ###############################################################

  - name: Deploy Bamboo objects to cluster
    command: kubectl -n {{namespace}} apply -f /tmp/k8s/bamboo

    # You can add extra conditional stuff here, example
    #when cluster_name in ["cluster1"]

  #- name: Clean up the directory
  #  file: path=/tmp/k8s/bamboo state=absent
  #  tags:
  #  - cleanup