apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{appname}}
  namespace: {{namespace}}
  labels:
    service: {{bambooservicename}}
    app: {{appname}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{appname}}
  template:
    metadata:
      labels:
        app: {{appname}}
    spec:
      containers:
        - name: bamboo
          image: dchevell/bamboo:latest
          imagePullPolicy: Always
          env:
            - name: JVM_MINIMUM_MEMORY
              value: {{jvmlow}}
            - name: JVM_MAXIMUM_MEMORY
              value: {{jvmhigh}}
            - name: PROXYNAME
              value: {{proxyname}}
            - name: PROXYSCHEME
              value: {{proxyscheme}}
            - name: PROXYSECURE
              value: "true"
          ports:
            - containerPort: 8085
          volumeMounts:
          - mountPath: "/var/atlassian/application-data/bamboo"
            name: {{bamboovolume}}
      volumes:
      - name: {{bamboovolume}}
        persistentVolumeClaim:
          claimName: {{bamboovolumeclaim}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{bambook8sservicename}}
  namespace: {{namespace}}
  labels:
    app: {{appname}}
spec:
  type:
  externalIPs:
  - {{ nodeip1 }}
  - {{ nodeip2 }}
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: {{appname}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{namespace}}
  name: {{bamboovolumename}}
spec:
  capacity:
    storage: {{storagesize}}
  accessModes:
  - ReadWriteMany
  nfs:
    server: {{nfsserverip}}
    path: {{nfspath}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{bamboovolumename}}
  namespace: {{namespace}}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{storagesize}}
