---
apiVersion: v1
kind: Service
metadata:
  name: jsd-external
  namespace: {{namespace}}
  labels:
    app: {{appname}}
spec:
  type: LoadBalancer
  externalIPs:
    - {{nodeip1}}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  sessionAffinity: ClientIP
  selector:
    app: {{appname}}