apiVersion: v1
kind: Service
metadata:
  name: {{appname}}
  namespace: {{namespace}}
  labels:
    app: {{appname}}
spec:
  selector:
    app: {{appname}}
  ports:
  - name: psql
    port: 5432
    targetPort: 5432
    protocol: TCP
