apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{namespace}}
  name: {{appname}}
spec:
  serviceName: {{appname}}
  replicas: 1
  selector:
    matchLabels:
      app: {{appname}}
  template:
    metadata:
      labels:
        app: {{appname}}
    spec:
      containers:
        - name: {{appname}}
          image: mbern/postgres-atlas-all:latest
          env:
            - name: POSTGRES_PASSWORD
              value: test123
          resources:
            requests:
              cpu: {{podcpu}}
              memory: {{podmemory}}
            limits:
              cpu: {{podcpu}}
              memory: {{podmemory}}
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data/"
              name: {{volume}}
      volumes:
        - name: {{volume}}
          persistentVolumeClaim:
            claimName: {{volumeclaim}}
